baseurl = "/" # Hostname (and path) to the root.
title = "Carl Centola" # Site title.
theme = "coder" # Set the theme.
languagecode = "en" # The site’s language code used to generate RSS.
defaultcontentlanguage = "en" # The default content language.

paginate = 20 # Default number of pages per page in pagination.
canonifyurls = true # Enable to turn relative URLs into absolute.

pygmentsstyle = "b2" # Color-theme or style for syntax highlighting.
pygmentscodefences = true # Enable code fence background highlighting.
pygmentscodefencesguesssyntax = true # Enable syntax guessing for code fences without specified language.

disqusShortname = "ccentola-github-io" # Enable or disable Disqus.
googleAnalytics = "UA-124215224-1" # Enables Google Analytics

[params] # theme parameters
    author = "Carl Centola" # Author's name.
    info = "Not a data analyst, not a developer" # Author's job title or info.
    description = "Carl Centola's personal website" # Site description.
    keywords = "blog,developer,personal" # Site keywords.
    avatarurl = "" # Contain the path of the optionnal avatar in the static folder.

    footercontent = "Less is more." # Add footer content

    # Whether you want to hide copyright and credits in the footer.
    hideCredits = true
    hideCopyright = false

    # Custom CSS
    custom_css = []

    # RTL support
    rtl = false

    # Multilanguage mode
    langseparator = "|" # Separates menus from language selectors when site is multilingual.

# Social links
[[params.social]]
    name = "Github"
    weight = 1
    icon = "fab fa-github-square fa-2x"
    url = "https://github.com/ccentola/"
[[params.social]]
    name = "LinkedIn"
    weight = 2
    icon = "fab fa-linkedin fa-2x"
    url = "https://www.linkedin.com/in/carlcentola/"
[[params.social]]
    name = "Contact"
    weight = 2
    icon = "fas fa-envelope fa-2x"
    url = "mailto:carl.centola@gmail.com"

# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/posts/"
[[menu.main]]
    name = "About"
    weight = 2
    url = "/about/"
[[menu.main]]
    name = "Projects"
    weight = 3
    url = "/projects/"
[[menu.main]]
    name = "Resources"
    weight = 4
    url = "/resources/"